OLED_ENABLE = no
ENCODER_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
ENCODER_MAP_ENABLE = no
LTO_ENABLE = yes
RGBLIGHT_ENABLE = no
QMK_SETTINGS = yes
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no


EXTRAFLAGS += -flto

